### ISSUE TITLE
Add Modules

### ISSUE THREAD

**Issue by albertski** [wodby/apache#6]
Is there a way to add more apache module?  I need to add `module_include` to a project I am working on.  Not sure what the best way to handle adding it.

**Comment by csandanov** [comment]
mod_include added in [4.0.4](https://github.com/wodby/apache/releases/tag/4.0.4), sounds like a module that should be in the image by default. If you need a very specific module you should use your own httpd.conf (either mount or build your image on top).

**Comment by sylven** [comment]
I'm using docker4drupal and I also needed to enable an apache module.
Excuse me if I shouldn't post this here but I've been browsing the issues from wodby/apache and wodby/docker4drupal and couldn't find anything to help me. I found something on the issues of wodby/docker4dwordpress and I think this might be useful to someone.

I needed to use ProxyPass and ProxyPassReverse, which needs both extensions 'mod_proxy' and 'mod_proxy_http'.
'mod_proxy_http' is not enabled, maybe because 'mod_proxy_http2' it is.

To enable 'mod_proxy_http' I had to add these lines to docker-compose.yml under apache container declaration:
```
environment:
  APACHE_INCLUDE_CONF: /usr/local/apache2/conf/custom-extra.conf
volumes: 
  - ./extra-apache2.conf:/usr/local/apache2/conf/custom-extra.conf
```
The content of 'extra-apache2.conf' has to be the virtual host from this template:
https://github.com/wodby/apache/blob/master/templates/vhost.conf.tmpl
And below that you can enable apache modules and add the ProxyPass rules you may need.

Not sure what is this ```{{ getenv "APACHE_DOCUMENT_ROOT" "/var/www/html" }}``` syntax but for some reason it wasn't picking it up, so I had to manually define the values instead of using dynamic conditionals.

**Comment by csandanov** [comment]
`proxy_module` is enabled, see https://github.com/wodby/apache/blob/master/tests/basic/apache_modules, you can check it yourself by running `httpd -M`

**Comment by sylven** [comment]
I know, but I needed also ```proxy_http_module```, which was not enabled.

**Comment by csandanov** [comment]
The module has been added
